plugins:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'Steepfile'

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/LineLength:
  Max: 128

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ParameterLists:
  Max: 8

Naming/AccessorMethodName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

RSpec/ExampleLength:
  Max: 16

RSpec/MultipleMemoizedHelpers:
  Max: 16

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/SpecFilePathFormat:
  Enabled: false

Security/MarshalLoad:
  Exclude:
    - 'spec/**/*'
